USE OnlineShopping;

INSERT INTO Product VALUES
('Wireless Air Mouse Pro C125 for Smart TV','1'),
('Smart Air Mouse MX5 Backlit for Android TV','1'),
('Mini RF Touch Keyboard with RGB Backlight','1'),
('Viboton Wireless Touch Keyboard S2','1'),
('Quad Core Android HDMI TV Stick MK810 2GB+8GB','1'),
('MXQ 4K Android Smart TV Box Quad Core','1'),
('MXQ Pro Ultra 4K Android TV Box 1GB+8GB','1'),
('NexBox A96 Quad Core Android TV Box 2GB+8GB','1'),
('H96 Pro Plus Octa Core Android TV Box 3GB+32GB','1'),
('H96 Max Ultra Android TV Box 4GB+32GB','1'),
('X96 Mini Android TV Box Quad Core 2GB+16GB','1'),
('Mecool K5 Pro Android TV Box Octa Core','1'),
('JS8 Air Mouse Keyboard with Touch Pad','1'),
('V88 Piano Android TV Box Quad Core 4GB+16GB','1'),
('MX4 Backlit Air Mouse for Smart TV','1'),
('H96 Max H3 Android TV Box 4GB+32GB','1'),
('Digital Persona USB Fingerprint Scanner U4500','2'),
('ZKTeco iFace 703 Biometric Device','2'),
('ZKTeco TX630 Attendance Terminal','2'),
('ZKTeco Live20R Optical Fingerprint Scanner','2'),
('ZKTeco K4600 USB Fingerprint Reader','2'),
('ZKTeco TX630 RFID Attendance Machine','2'),
('iFace 703 Replacement Battery','2'),
('Digital Persona Optical Fingerprint Scanner U5200','2'),
('SpeedX 3200 Bluetooth Barcode Scanner','3'),
('SpeedX 6200 2D Handheld Barcode Scanner','3'),
('SpeedX 9300 Desktop 2D Barcode Scanner','3'),
('SpeedX 9150 Desktop Barcode Scanner','3'),
('SpeedX 8150 Auto Scan Barcode Reader','3'),
('SpeedX 8250 Wired Barcode Scanner','3'),
('SpeedX 5200 WiFi Barcode Scanner','3'),
('SpeedX 310 Thermal Receipt Printer USB+LAN','3'),
('SpeedX 210 Thermal Receipt Printer USB','3'),
('Thermal Printer Controller Board USB+RS232','3'),
('Thermal Printer Controller Board USB+LAN','3'),
('XPrint X9400 Barcode Scanner','3'),
('Universal Barcode Scanner Stand','3'),
('Remax T8 Pro Bluetooth Earphones Black','4'),
('Remax T8 Pro Bluetooth Earphones White','4'),
('LG Tone HBS 910 Wireless Neckband','4'),
('LG Tone HBS 740 Bluetooth Handsfree','4'),
('Beats Power3 Wireless Earphones','4'),
('LG Tone Ultra HBS 820 Neckband','4'),
('Remax RB T4 Bluetooth Handsfree','4'),
('Remax RB T6 Bluetooth Handsfree','4'),
('Remax RBT8 Wireless Earphones','4'),
('UrBeats Wireless Bluetooth Earphones','4'),
('Remax T10 Bluetooth Headset','4'),
('Mi Wireless Bluetooth Headset Pro','4'),
('Remax Bluetooth Earphones T11','4'),
('Remax S3 Magnetic Sports Earphones','4'),
('Remax S9 Sports Neckband Bluetooth','4'),
('Remax T14 Wireless Handsfree','4'),
('True Wireless Earbuds V5 H10','4'),
('Baseus Wireless Earbuds NGA03','4'),
('Baseus Encok Mini TWS Earbuds NGA05','4'),
('Baseus Magnetic Bluetooth Neckband','4'),
('True Wireless Earbuds I9','4'),
('True Wireless Bluetooth Earbuds IP9','4'),
('Beats Studio Wireless Headphones TM011','5'),
('Nia Q2 Wireless Bluetooth Headphones','5'),
('Nia X3 Bluetooth Headphones Black','5'),
('Beats Wireless Headphones TM020','5'),
('Bluedio H+ Turbo Bluetooth Headphones','5'),
('Bluedio T3 Plus Wireless Headphones','5'),
('JBL Wireless Headphones S995','5'),
('JBL QuietComfort Wireless QC36','5'),
('Bose QuietComfort Wireless QC960','5'),
('Remax 200HB Bluetooth Headphones','5'),
('Sony Wireless Bluetooth Headphones SBH70','5'),
('Nia X6 Bluetooth Speaker Headphones','5'),
('Beats Studio Wireless 4 Headphones','5'),
('Beats Solo4 Wireless Headphones','5'),
('Bose SoundLink Mini II Bluetooth Speaker','6'),
('Beats Pill Plus Wireless Speaker','6'),
('Bose Touch Bluetooth Speaker BE9','6'),
('JBL Charge 2 Wireless Speaker','6'),
('Rock Portable Bluetooth Speaker B16','6'),
('JBL Charge 4 Wireless Speaker','6'),
('Bose SoundLink Plus Bluetooth Speaker','6'),
('Rock HFQ7 Bluetooth Speaker','6'),
('Remax RBM15 Portable Speaker','6'),
('Aero Bull Portable Bluetooth Speaker','6'),
('Portable Bluetooth Speaker BS135','6'),
('JBL Round Bluetooth Speaker BS05','6'),
('Havit Wireless Bluetooth Speaker','6'),
('Daniu LED Bluetooth Speaker','6'),
('JBL K7 Bluetooth Speaker','6'),
('JBL Charge Mini 4 Bluetooth Speaker','6'),
('Romoss Sense 5 10000mAh Power Bank','7'),
('Romoss Sense 7 20000mAh Power Bank','7'),
('Romoss Sense 10 25000mAh Power Bank','7'),
('Mi Power Bank 3 10000mAh Black','7'),
('Mi Power Bank 3 Pro 20000mAh','7'),
('Aspor Slim Power Bank 6000mAh A374','7'),
('Aspor Slim Power Bank 10000mAh A384','7'),
('Mi Power Bank 3 10000mAh Silver','7'),
('Aspor Fast Charge Power Bank 10000mAh Black','7'),
('Romoss RT12 Pro 10000mAh Fast Charge','7'),
('Aspor Fast Charge Power Bank 10000mAh Silver','7'),
('USB Endoscope Camera 3.5M for Android & PC','8'),
('Remax Dash Cam CX02 Full HD','8'),
('Wireless IP Camera 360 Dual Antenna','8'),
('4K WiFi Action Sports Camera','8'),
('Car DVR Dual Camera Front & Rear','8'),
('Panoramic IP Fish Eye Camera V390','8'),
('Car DVR Mirror Touch Screen Camera','8'),
('3D Panoramic WiFi IP Camera IPC370','8'),
('Outdoor Waterproof IP Bullet Camera 8120','8'),
('Smart Video Doorbell WiFi Camera','8'),
('DZ10 Android Smart Watch Black','9'),
('DZ10 Android Smart Watch Gold','9'),
('W09 Android Smart Watch Black','9'),
('W09 Android Smart Watch White','9'),
('GT09 Android Smart Watch Black','9'),
('Mi Band 3 Fitness Tracker','9'),
('GT09 Android Smart Watch Silver','9'),
('Q91 GPS Smart Watch with WiFi','9'),
('GT09 Plus Android Smart Watch 3G','9'),
('X02 Android Smart Watch 3G','9'),
('Y2 Smart Watch with SIM & Camera','9'),
('Smart Watch Battery X02','9'),
('Smart Watch Battery DZ10','9'),
('Health Smart Watch 120HR','9'),
('Smart Fitness Band K2 Black','9'),
('Smart Fitness Band K2 Blue','9'),
('Smart Watch Battery Z60','9'),
('X03 Android Smart Watch 5.1','9'),
('Heart Rate Fitness Band Y08','9'),
('USB 3.0 Magnetic Hub 4 Port U308','10'),
('USB 3.0 Hub 4 Port U314','10'),
('USB 3.0 Hub 4 Port U305','10'),
('USB Hub 7 Port 2.0 with Power Switch','10'),
('12 Port USB Fast Charger 15A','10'),
('USB 2.0 Magnetic Hub 4 Port U208','10'),
('USB Hub 4 Port with Power Button','10'),
('Remax 6 Port USB Charging Hub','10'),
('USB 3.0 Hub 7 Port with Switch','10'),
('ORICO USB 3.0 Hub 4 Port W60','10');
